baseurl = "https://www.salvatoremalatesta.com.au"
languageCode = "en-us"
title = "Salvatore Malatesta"

[params]
  jo = "Joanne"
  sal = "Salvatore"
  surname = "Malatesta"
  imgcdn = "https://res.cloudinary.com/stali/image/upload/f_auto,q_85"
  imgsrc = "img/opti"
  jophoto = "joanne-malatesta-art"
  salphoto = "salvatore-malatesta-art"
  author = "STOQE"
  metaDescription = "The official website of Salvatore Malatesta."
  metaDescriptionAbout = "All about Salvatore Malatesta."
  metaDescriptionJo = "Joanne Malatesta, formerly Joanne Spain. Wife of Salvatore."
  metaDescriptionMedia = "Official"
  metaDescriptionSocial = "Follow Sal on Twitter, Instagram, LinkedIn, and more."


